name: Publish Salez CE docker images for AMD64
on:
  push:
    branches:
      - main
      - staging
      - development
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag da versão (ex: v4.0.1). Se vazio, usará a branch/tag do Git.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }} # ref_name to get tags/branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      # Extrair a versão do package.json
      - name: Extrair versão do package.json
        id: package_version
        run: |
          APP_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[:space:]')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "Versão do package.json: $APP_VERSION"

      - name: Set docker tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          if [ -z "$VERSION" ]; then
            VERSION=$GIT_REF
          fi
          echo "DOCKER_TAG=saleztechnology/salez_v4:$VERSION" >> $GITHUB_ENV

      - name: Replace docker tag if main
        if: github.ref_name == 'main'
        run: |
          echo "DOCKER_TAG=saleztechnology/salez_v4:latest" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: saleztechnology
          password: dckr_pat_mySJ4YUFFMPHG19nqvqYpgpa24g

      - name: Build and push amd64 image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAG }}
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
